# Generated by Django 4.2.2 on 2023-06-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daters", "0002_dateruser_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="dateruser",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="dateruser",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
