# Generated by Django 4.2.2 on 2023-06-29 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daters", "0003_dateruser_latitude_dateruser_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dateruser",
            name="latitude",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dateruser",
            name="longitude",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
    ]
